# Generated by Django 5.2.14 on 2026-05-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='track_temp_c',
        ),
        migrations.AddField(
            model_name='raceresult',
            name='avg_pit_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время пит-стопа'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='laps',
            field=models.IntegerField(default=0, verbose_name='Круги'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='track_temp',
            field=models.FloatField(null=True, verbose_name='Температура трассы'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='constructor',
            field=models.CharField(max_length=100, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='driver',
            field=models.CharField(max_length=100, verbose_name='Пилот'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='race_name',
            field=models.CharField(max_length=255, verbose_name='Гонка'),
        ),
    ]
