# Generated by Django 5.2.14 on 2026-05-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Сезон')),
                ('race_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=100)),
                ('constructor', models.CharField(max_length=100)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('track_temp_c', models.FloatField(null=True)),
                ('is_completed', models.BooleanField(default=True)),
            ],
        ),
    ]
